---
title: "Tidy Data"
author: "Fang Wang"
date: "2024-09-24"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, message = FALSE}
setwd("/Users/fangwang/Downloads/P8105 Data Science I/Lecture 7/Tidy Data")
library(tidyverse)
library(haven)
```

This document will show how to tidy data.

## "pivot_longer"
Load "PULSE" data and this needs to go from wide format to long format...

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit", # new variable is called "visit".
    names_prefix = "bdi_score_",# remove the prefix.
    values_to = "bdi_score"
  ) |> 
  mutate (
    visit = replace (visit, visit == "bl", "00m")
  ) |> 
  relocate(id, visit) # show "id" and "visit" as the first two columns.
```

Do one more example.

```{r}
litters_df =
  read_csv ("data/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = gd0_weight: gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  ) |> 
  mutate(
    gd_time = case_match( # here, case_match is used to change the values in the variable.
      gd_time,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
```

## pivot wider

Let's make up an analysis result table.
```{r}
analysis_df =
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
```

pivot wider for human readability. This function is used less than pivot longer, but it is useful for treatment/control analysis.

```{r}
analysis_df |> 
  pivot_wider(
    names_from = time,
    values_from = mean
  ) |> 
  knitr::kable() # to knit into a table
```



